version: '3.4'

services:
  retrobot:
    image: retrobot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["npm", "--inspect=0.0.0.0:9229", "start"]
